# Custom Language File for Launcher Customizer

[ejs.app]
title = "Mystian Launcher"

[ejs.landing]
mediaGitHubURL = "https://www.mystianfields.net/"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/D2cabqkU3m"

[ejs.settings]
sourceGithubLink = "#"
supportLink = "#"

[ejs.welcome]
welcomeHeader = "Welcome to Mystian Fields!"
welcomeDescription = "WAAAAAAAAAAA"
welcomeDescCTA = "Mystian Edition made easy"
